Repository caas-team/GoKubeDownscaler, pull requests merged in 2024-10, with the labels that each got.

#62 fix: embed tzdata in binary
  cmd/kubedownscaler/main.go
  deployments/chart/Chart.yaml
Labels: bug, new release

#65 Fix/serviceaccount creation
  .github/workflows/check_for_release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_dev_build.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  deployments/chart/Chart.yaml
  deployments/chart/templates/serviceaccount.yaml
Labels: housekeeping

#66 fix: invalid email in pre commit workflow
  .github/workflows/pre_commit.yaml
Labels: bug
