Repository caas-team/GoKubeDownscaler, pull requests merged in 2024-09, with the labels that each got.

#22 Feat/add helm chart
  .github/workflows/helm_build.yaml
  .pre-commit-config.yaml
  deployments/chart/.helmignore
  deployments/chart/Chart.yaml
  deployments/chart/README.md
  deployments/chart/templates/_helpers.tpl
  deployments/chart/templates/clusterrole.yaml
  deployments/chart/templates/configmap.yaml
  deployments/chart/templates/deployment.yaml
  deployments/chart/templates/role.yaml
  deployments/chart/templates/serviceaccount.yaml
  deployments/chart/values.yaml
Labels: enhancement

#28 Feat/improved readme
  .github/ISSUE_TEMPLATE/issue-tempate.md
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  deployments/chart/README.md
  deployments/chart/values.yaml
  internal/api/kubernetes/client.go
  internal/pkg/values/layer.go
  internal/pkg/values/layer_test.go
  internal/pkg/values/timespan.go
  internal/pkg/values/util.go
Labels: documentation, enhancement

#40 fix: small issues in readme
  README.md
  deployments/chart/README.md
Labels: bug, documentation, enhancement

#44 Enhance CI Workflow: Check for Version Bump and appVersion Changes
  .github/workflows/check-for-release.yaml
Labels: enhancement

#31 Feat/Add Resources (StatefulSets, DaemonSets, HPA, PodDisruptionBudgets, CronJobs, Jobs, Keda ScaledObjects)
  go.mod
  go.sum
  internal/api/kubernetes/client.go
  internal/pkg/scalable/cronjobs.go
  internal/pkg/scalable/cronjobs_test.go
  internal/pkg/scalable/daemonsets.go
  internal/pkg/scalable/daemonsets_test.go
  internal/pkg/scalable/deployments.go
  internal/pkg/scalable/deployments_test.go
  internal/pkg/scalable/helpers_test.go
  internal/pkg/scalable/horizontalpodautoscalers.go
  internal/pkg/scalable/horizontalpodautoscalers_test.go
  internal/pkg/scalable/jobs.go
  internal/pkg/scalable/jobs_test.go
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/poddisruptionbudgets_test.go
  internal/pkg/scalable/scalableResource.go
  internal/pkg/scalable/scaledobjects.go
  internal/pkg/scalable/scaledobjects_test.go
  internal/pkg/scalable/statefulsets.go
  internal/pkg/scalable/statefulsets_test.go
  internal/pkg/scalable/util.go
Labels: missing feature

#45 feat: add pre commit workflow
  .github/workflows/go_test.yaml
  .github/workflows/pre_commit.yaml
  deployments/chart/Chart.yaml
Labels: enhancement

#48 create auto assign workflow
  .github/pull_request_template.md
  .github/workflows/auto_assign_author.yaml
Labels: enhancement

#37 Feat/implement missing values
  .prettierignore
  CONTRIBUTING.md
  README.md
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  internal/api/kubernetes/client.go
  internal/api/kubernetes/resourceLogger.go
  internal/pkg/scalable/scalableResource.go
  internal/pkg/scalable/util.go
  internal/pkg/scalable/util_test.go
  internal/pkg/values/layer.go
  internal/pkg/values/layer_test.go
  internal/pkg/values/regexList.go
  internal/pkg/values/util.go
Labels: missing feature

#42 Feat/refactor workflows
  .github/workflows/check-for-release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_release.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  deployments/chart/Chart.yaml
Labels: enhancement, new release

#49 Revert "Feat/refactor workflows"
  .github/workflows/check-for-release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_release.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  deployments/chart/Chart.yaml
Labels: bug

#50 Feat/refactor workflows
  .github/workflows/check-for-release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_release.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  deployments/chart/Chart.yaml
Labels: new release

#51 Revert "Feat/refactor workflows"
  .github/workflows/check-for-release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_release.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  deployments/chart/Chart.yaml
Labels: bug

#52 Feat/refactor workflows
  .github/workflows/check-for-release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_release.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  deployments/chart/Chart.yaml
Labels: enhancement, new release

#54 feat: let workflow trigger on label removal
  .github/workflows/check-for-release.yaml
Labels: enhancement, housekeeping

#57 fix: CMD gets overwritten by args
  Dockerfile
  deployments/chart/Chart.yaml
Labels: bug, new release

#58 fix: let workflow not trigger on labels
  .github/workflows/check-for-release.yaml
Labels: bug, enhancement, housekeeping

#59 fix: dockerfile binary not found
  Dockerfile
  deployments/chart/Chart.yaml
Labels: bug, new release

#55 feat/add more workload types
  Dockerfile
  README.md
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  deployments/chart/.helmignore
  deployments/chart/Chart.yaml
  deployments/chart/README.md
  deployments/chart/icon.svg
  deployments/chart/templates/_helpers.tpl
  docs/troubleshooting.md
  go.mod
  go.sum
  internal/api/kubernetes/client.go
  internal/pkg/scalable/cronjobs.go
  internal/pkg/scalable/daemonsets.go
  internal/pkg/scalable/deployments.go
  internal/pkg/scalable/helpers_test.go
  internal/pkg/scalable/horizontalpodautoscalers.go
  internal/pkg/scalable/horizontalpodautoscalers_test.go
  internal/pkg/scalable/jobs.go
  internal/pkg/scalable/jobs_test.go
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/poddisruptionbudgets_test.go
  internal/pkg/scalable/prometheuses.go
  internal/pkg/scalable/replicaScaledWorkloads.go
  internal/pkg/scalable/replicaScaledWorkloads_test.go
  internal/pkg/scalable/rollouts.go
  internal/pkg/scalable/scaledobjects.go
  internal/pkg/scalable/scaledobjects_test.go
  internal/pkg/scalable/stacks.go
  internal/pkg/scalable/statefulsets.go
  internal/pkg/scalable/statefulsets_test.go
  internal/pkg/scalable/suspendScaledWorkloads.go
  internal/pkg/scalable/suspendScaledWorkloads_test.go
  internal/pkg/scalable/util.go
  internal/pkg/scalable/util_test.go
  internal/pkg/scalable/workload.go
  internal/pkg/values/durationValue.go
  internal/pkg/values/int32Value.go
  internal/pkg/values/layer.go
  internal/pkg/values/stringlistValue.go
  internal/pkg/values/util.go
Labels: enhancement, missing feature, new release
