Repository caas-team/GoKubeDownscaler, pull requests merged in 2025-03, with the labels that each got.

#130 Refactor/added release namespace in the objects of the helm chart
  .pre-commit-config.yaml
  deployments/chart/templates/configmap.yaml
  deployments/chart/templates/deployment.yaml
  deployments/chart/templates/leaserole.yaml
  deployments/chart/templates/serviceaccount.yaml
  internal/pkg/util/config.go
Labels: enhancement, housekeeping

#118 Refactor/timespans and layer defaults
  .golangci.yaml
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  internal/pkg/util/config.go
  internal/pkg/values/dayTime.go
  internal/pkg/values/layer.go
  internal/pkg/values/layer_test.go
  internal/pkg/values/timespan.go
  internal/pkg/values/timespan_test.go
Labels: housekeeping

#134 Feat/improve documentation on order of arguments
  .markdownlint-cli2.yaml
  .pre-commit-config.yaml
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  internal/pkg/values/scope.go
  internal/pkg/values/scopeParser.go
  internal/pkg/values/scope_test.go
  website/content/docs/0 - downscaler/0 - Arguments.mdx
  website/content/docs/0 - downscaler/1 - Environment Variables.mdx
  website/content/docs/0 - downscaler/2 - Annotations.mdx
  website/content/docs/0 - downscaler/4 - Values.mdx
  website/content/docs/0 - downscaler/5 - Layers.mdx
  website/content/docs/0 - downscaler/5 - Scopes.mdx
  website/content/docs/0 - downscaler/6 - types/0 - Timespans.mdx
  website/content/docs/0 - downscaler/assets/layer-diagram.png
  website/content/docs/0 - downscaler/assets/scope-diagram.excalidraw
  website/content/docs/1 - helm-chart/2 - values/1 - image.mdx
  website/content/docs/1 - helm-chart/2 - values/2 - arguments.mdx
  website/content/guides/1 - developing/1 - Website.mdx
  website/content/guides/1 - developing/assets/example.excalidraw
  website/content/guides/2 - Migrating from py-kube-downscaler.mdx
  website/docusaurus.config.ts
  website/package-lock.json
  website/package.json
  website/plugins/conf-webpack.cts
  website/plugins/global-ref-plugin.cts
  website/src/components/Excalidraw/Excalidraw.tsx
  website/src/components/Excalidraw/ExcalidrawRenderer.tsx
  website/src/types/components/GithubLabel.d.ts
  website/src/types/components/common.d.ts
Labels: enhancement

#132 Feat/allow timespans in force up and downtime + fix everything
  .golangci.yaml
  go.mod
  go.sum
  internal/pkg/scalable/prometheuses.go
  internal/pkg/values/layer.go
  internal/pkg/values/layerParser.go
  internal/pkg/values/layer_test.go
  internal/pkg/values/timespan.go
  internal/pkg/values/timespan_test.go
  internal/pkg/values/triStateBool.go
Labels: enhancement, blocked

#74 Feat/retries on conflict error
  README.md
  cmd/kubedownscaler/main.go
  docs/troubleshooting.md
  go.mod
  go.sum
  internal/api/kubernetes/client.go
  internal/pkg/scalable/cronjobs.go
  internal/pkg/scalable/daemonsets.go
  internal/pkg/scalable/deployments.go
  internal/pkg/scalable/horizontalpodautoscalers.go
  internal/pkg/scalable/jobs.go
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/prometheuses.go
  internal/pkg/scalable/rollouts.go
  internal/pkg/scalable/scaledobjects.go
  internal/pkg/scalable/stacks.go
  internal/pkg/scalable/statefulsets.go
  internal/pkg/scalable/workload.go
  internal/pkg/util/config.go
Labels: enhancement

#146 chore: bump deps
  go.mod
  go.sum
Labels: dependencies

#144 fix: err on missing time annotation
  internal/pkg/values/scope.go
  internal/pkg/values/scope_test.go
Labels: bug

#160 Feat/add config reload
  deployments/chart/templates/deployment.yaml
  deployments/chart/values.yaml
  website/content/docs/1 - helm-chart/0 - Components.mdx
  website/content/docs/1 - helm-chart/2 - values/16 - excludedNamespaces.mdx
  website/content/docs/1 - helm-chart/2 - values/17 - configMap.mdx
  website/content/docs/1 - helm-chart/2 - values/18 - forceRestartOnConfigChange.mdx
Labels: enhancement

#161 Refactor/workflows
  .github/workflows/check_for_release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_dev_build.yaml
  .github/workflows/create_release.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  website/content/docs/2 - Workflows.mdx
Labels: housekeeping

#159 chore: release v1.2.0
  .github/workflows/check_for_release.yaml
  deployments/chart/Chart.yaml
Labels: new release, housekeeping

#164 chore: fix package name
  .github/workflows/docker_build.yaml
  .github/workflows/prune.yaml
Labels: bug

#166 chore: add cosign prune action
  .github/workflows/prune.yaml
Labels: enhancement

#167 chore: add keep younger than
  .github/workflows/prune.yaml
Labels: enhancement

#176 Feat/multi-arch build
  .github/workflows/docker_build.yaml
  deployments/chart/Chart.yaml
Labels: enhancement, new release
