Repository caas-team/GoKubeDownscaler, pull requests merged in 2025-01, with the labels that each got.

#77 fix: make workflows run for forks
  .github/workflows/auto_assign_author.yaml
  .github/workflows/check_for_release.yaml
Labels: bug

#83 chore: add dependabot config
  .github/dependabot.yml
Labels: housekeeping

#81 perf: reduce memory allocations
  internal/api/kubernetes/client.go
  internal/pkg/scalable/cronjobs.go
  internal/pkg/scalable/daemonsets.go
  internal/pkg/scalable/deployments.go
  internal/pkg/scalable/horizontalpodautoscalers.go
  internal/pkg/scalable/jobs.go
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/prometheuses.go
  internal/pkg/scalable/rollouts.go
  internal/pkg/scalable/scaledobjects.go
  internal/pkg/scalable/stacks.go
  internal/pkg/scalable/statefulsets.go
  internal/pkg/values/regexList.go
  internal/pkg/values/stringlistValue.go
  internal/pkg/values/timespan.go
Labels: housekeeping

#80 Feat/add md lint
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .github/workflows/pre_commit.yaml
  .markdownlint-cli2.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  deployments/chart/README.md
  website/content/docs/0 - downscaler/0 - Arguments.mdx
  website/content/docs/0 - downscaler/1 - Environment Variables.mdx
  website/content/docs/0 - downscaler/3 - Runtime Configuration.mdx
  website/content/docs/0 - downscaler/4 - Values.mdx
  website/content/docs/0 - downscaler/5 - Layers.mdx
  website/content/docs/0 - downscaler/6 - types/0 - Timespans.mdx
  website/content/docs/0 - downscaler/6 - types/3 - Regex List.mdx
  website/content/docs/0 - downscaler/7 - Workload Types.mdx
  website/content/docs/0 - helm-chart/0 - Components.mdx
  website/content/docs/1 - helm-chart/0 - Components.mdx
  website/content/docs/1 - helm-chart/1 - Permissions.mdx
  website/content/docs/1 - helm-chart/2 - values/0 - replicaCount.mdx
  website/content/docs/1 - helm-chart/2 - values/1 - image.mdx
  website/content/docs/1 - helm-chart/2 - values/10 - securityContext.mdx
  website/content/docs/1 - helm-chart/2 - values/11 - resources.mdx
  website/content/docs/1 - helm-chart/2 - values/12 - nodeSelector.mdx
  website/content/docs/1 - helm-chart/2 - values/13 - tolerations.mdx
  website/content/docs/1 - helm-chart/2 - values/14 - affinity.mdx
  website/content/docs/1 - helm-chart/2 - values/15 - excludedNamespaces.mdx
  website/content/docs/1 - helm-chart/2 - values/16 - configMap.mdx
  website/content/docs/1 - helm-chart/2 - values/2 - arguments.mdx
  website/content/docs/1 - helm-chart/2 - values/3 - includedResources.mdx
  website/content/docs/1 - helm-chart/2 - values/4 - fullnameOverride.mdx
  website/content/docs/1 - helm-chart/2 - values/5 - nameOverride.mdx
  website/content/docs/1 - helm-chart/2 - values/6 - constrainedDownscaler.mdx
  website/content/docs/1 - helm-chart/2 - values/7 - constrainedNamespaces.mdx
  website/content/docs/1 - helm-chart/2 - values/8 - serviceAccount.mdx
  website/content/docs/1 - helm-chart/2 - values/9 - podSecurityContext.mdx
  website/content/docs/1 - helm-chart/2 - values/index.mdx
  website/content/docs/1 - helm-chart/index.mdx
  website/content/docs/2 - Workflows.mdx
  website/content/guides/0 - getting-started/0 - Installation.mdx
  website/content/guides/1 - developing/1 - Website.mdx
  website/content/guides/1 - developing/3 - Maintaining the Repository.mdx
  website/content/guides/1 - developing/index.mdx
  website/content/guides/2 - Migrating from py-kube-downscaler.mdx
  website/eslint.config.mjs
  website/package-lock.json
  website/package.json
  website/src/pages/docs.mdx
  website/src/pages/guides.mdx
Labels: enhancement, housekeeping

#93 Refactor/enforce stricter go linters
  .golangci.yaml
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  internal/api/kubernetes/client.go
  internal/api/kubernetes/resourceLogger.go
  internal/api/kubernetes/util.go
  internal/pkg/scalable/cronjobs.go
  internal/pkg/scalable/daemonsets.go
  internal/pkg/scalable/daemonsets_test.go
  internal/pkg/scalable/deployments.go
  internal/pkg/scalable/helpers_test.go
  internal/pkg/scalable/horizontalpodautoscalers.go
  internal/pkg/scalable/jobs.go
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/poddisruptionbudgets_test.go
  internal/pkg/scalable/prometheuses.go
  internal/pkg/scalable/replicaScaledWorkloads.go
  internal/pkg/scalable/replicaScaledWorkloads_test.go
  internal/pkg/scalable/rollouts.go
  internal/pkg/scalable/scaledobjects.go
  internal/pkg/scalable/stacks.go
  internal/pkg/scalable/statefulsets.go
  internal/pkg/scalable/suspendScaledWorkloads.go
  internal/pkg/scalable/suspendScaledWorkloads_test.go
  internal/pkg/scalable/util.go
  internal/pkg/scalable/util_test.go
  internal/pkg/scalable/workload.go
  internal/pkg/util/config.go
  internal/pkg/util/durationValue.go
  internal/pkg/util/env.go
  internal/pkg/util/int32Value.go
  internal/pkg/util/regexList.go
  internal/pkg/util/resourceLogger.go
  internal/pkg/util/stringlistValue.go
  internal/pkg/values/layer.go
  internal/pkg/values/layerParser.go
  internal/pkg/values/layer_test.go
  internal/pkg/values/timespan.go
  internal/pkg/values/timespan_test.go
  internal/pkg/values/triStateBool.go
  internal/pkg/values/util.go
Labels: housekeeping

#78 Feat/exclude externally scaled workloads
  internal/api/kubernetes/client.go
  internal/pkg/scalable/util.go
  internal/pkg/scalable/util_test.go
  internal/pkg/scalable/workload.go
Labels: bug
