Repository caas-team/GoKubeDownscaler, pull requests merged in 2025-02, with the labels that each got.

#100 Refactor/logs by adding stringers
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/scaledobjects.go
  internal/pkg/util/util.go
  internal/pkg/values/layer.go
  internal/pkg/values/timespan.go
  internal/pkg/values/triStateBool.go
Labels: enhancement, housekeeping

#101 fix: env vars parsing for runtime config
  cmd/kubedownscaler/main.go
Labels: bug

#107 feat: add groups for dependabot updates
  .github/dependabot.yml
Labels: enhancement, housekeeping

#75 Feat/leader election mechanism using leases
  cmd/kubedownscaler/main.go
  deployments/chart/templates/_helpers.tpl
  deployments/chart/templates/deployment.yaml
  deployments/chart/templates/leaserole.yaml
  deployments/chart/values.yaml
  internal/api/kubernetes/client.go
  internal/api/kubernetes/util.go
  internal/pkg/util/config.go
Labels: enhancement

#123 Fix: correction for leader election flag assignment
  internal/pkg/util/config.go
Labels: bug

#126 Feat/update issue template to include docs section
  .github/ISSUE_TEMPLATE/1-general.md
  .github/ISSUE_TEMPLATE/2-question.md
  .github/ISSUE_TEMPLATE/config.yml
  .pre-commit-config.yaml
Labels: enhancement, housekeeping
