Repository caas-team/GoKubeDownscaler, pull requests merged in 2025-04, with the labels that each got.

#180 fix: role creation
  deployments/chart/templates/role.yaml
Labels: bug

#142 Feat/avoid parsing namespace scope multiple times
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  internal/api/kubernetes/client.go
  internal/api/kubernetes/logger.go
  internal/api/kubernetes/resourceLogger.go
  internal/pkg/values/scope.go
Labels: enhancement, housekeeping, perf

#198 Feat/improve error handling
  cmd/kubedownscaler/errors.go
  cmd/kubedownscaler/main.go
  cmd/kubedownscaler/main_test.go
  internal/api/kubernetes/client.go
  internal/pkg/scalable/cronjobs.go
  internal/pkg/scalable/daemonsets.go
  internal/pkg/scalable/deployments.go
  internal/pkg/scalable/errors.go
  internal/pkg/scalable/horizontalpodautoscalers.go
  internal/pkg/scalable/jobs.go
  internal/pkg/scalable/poddisruptionbudgets.go
  internal/pkg/scalable/poddisruptionbudgets_test.go
  internal/pkg/scalable/prometheuses.go
  internal/pkg/scalable/replicaScaledWorkloads.go
  internal/pkg/scalable/replicaScaledWorkloads_test.go
  internal/pkg/scalable/rollouts.go
  internal/pkg/scalable/stacks.go
  internal/pkg/scalable/statefulsets.go
  internal/pkg/scalable/util.go
  internal/pkg/scalable/workload.go
  internal/pkg/values/dayTime.go
  internal/pkg/values/errors.go
  internal/pkg/values/scope.go
  internal/pkg/values/timespan.go
Labels: enhancement, housekeeping

#200 Fix/security findings
  .github/workflows/check_for_release.yaml
  .github/workflows/check_version.yaml
  .github/workflows/create_dev_build.yaml
  .github/workflows/deploy_website.yaml
  .github/workflows/docker_build.yaml
  .github/workflows/helm_build.yaml
  .github/workflows/validate_website_build.yaml
Labels: housekeeping

#202 fix: permissions for label removal
  .github/workflows/check_for_release.yaml
Labels: bug
